const sharedVariables = {
  colorBackground: "transparent",
  colorForeground: "#ffffff",
  colorPrimary: "#ffffff",
  colorPrimaryForeground: "#0a0a0a",
  colorMutedForeground: "rgba(255, 255, 255, 0.55)",
  colorDanger: "#cc3333",
  colorNeutral: "rgba(255, 255, 255, 0.38)",
  colorInput: "rgba(255, 255, 255, 0.06)",
  colorInputForeground: "#ffffff",
  colorBorder: "rgba(255, 255, 255, 0.38)",
  borderRadius: "0.625rem",
} as const

export const baseClerkAppearance = {
  variables: {
    ...sharedVariables,
    colorBackground: "#000000",
  },
  elements: {
    modalContent: "glass-popover",
    navbar: "bg-transparent",
    headerTitle: "text-metallic",
  },
} as const

export const authPageClerkAppearance = {
  variables: sharedVariables,
  options: {
    socialButtonsPlacement: "bottom",
    socialButtonsVariant: "blockButton",
  },
  elements: {
    rootBox: "tw-auth-root",
    cardBox: "tw-auth-card-box",
    card: "tw-auth-card",
    header: "tw-auth-header",
    headerTitle: "tw-auth-header",
    headerSubtitle: "tw-auth-header",
    logoBox: "tw-auth-header",
    main: "tw-auth-main",
    form: "tw-auth-form",
    formFieldRow: "tw-auth-field-row",
    formField: "tw-auth-field",
    formFieldLabel: "tw-auth-field-label",
    formFieldInput: "tw-auth-field-input",
    formButtonPrimary: {
      backgroundColor: "#ffffff",
      color: "#0a0a0a",
      fontWeight: 700,
      width: "100%",
      borderRadius: "0.75rem",
      paddingTop: "0.75rem",
      paddingBottom: "0.75rem",
      border: "1px solid #ffffff",
      boxShadow: "inset 0 1px 0 #ffffff, 0 1px 3px rgba(0, 0, 0, 0.25)",
      "&:hover": {
        backgroundColor: "#ffffff",
        color: "#0a0a0a",
        borderColor: "#ffffff",
      },
      "&:focus-visible": {
        backgroundColor: "#ffffff",
        color: "#0a0a0a",
        borderColor: "#ffffff",
      },
    },
    dividerLine: "tw-auth-divider-line",
    dividerText: "tw-auth-divider-text",
    socialButtonsRoot: "tw-auth-social-root",
    socialButtons: "tw-auth-social-buttons",
    socialButtonsIconButton: "tw-auth-social-icon",
    socialButtonsBlockButton: "tw-auth-social-block",
    lastAuthenticationStrategyBadge: {
      position: "absolute",
      top: 0,
      right: 0,
      insetInlineEnd: 0,
      left: "auto",
      transform: "translate(25%, -50%)",
      zIndex: 2,
      margin: 0,
      padding: "0.0625rem 0.375rem",
      height: "auto",
      fontSize: "0.5625rem",
      fontWeight: 500,
      lineHeight: "0.875rem",
      color: "rgba(255, 255, 255, 0.78)",
      background: "#1c1c1c",
      border: "1px solid rgba(255, 255, 255, 0.28)",
      borderRadius: "9999px",
      boxShadow: "0 1px 2px rgba(0, 0, 0, 0.45)",
      whiteSpace: "nowrap",
      pointerEvents: "none",
    },
    footer: "tw-auth-footer",
    footerAction: "tw-auth-footer-action",
    footerActionText: "tw-auth-footer-text",
    footerActionLink: "tw-auth-footer-link",
    footerItem: "tw-auth-footer-item",
    identityPreviewEditButton: "tw-auth-footer-link",
  },
}

export const clerkProviderAppearance = baseClerkAppearance
